pipeline {
    options {
        // set a timeout of 30 minutes for this pipeline
        timeout(time: 30, unit: 'MINUTES')
    }
    agent any
      tools {nodejs "nodejs1"}

    stages {

        stage('stage 1') {
            steps {
                script {
                    openshift.withCluster() {
                        openshift.withProject() {
                                echo "stage 1: using project: ${openshift.project()} in cluster ${openshift.cluster()}"
                        }
                    }
                }
            }
        }

        stage('stage 2') {
        steps {
            sh 'echo hello from stage 2!. This is the last stage...'
        }
    }

    stage('Manual Approval') {
        steps {
                timeout(time: 1, unit: 'MINUTES'){
        input message : "Move to step 3?"
      }

        }
    }

        stage('stage 3') {
            steps {
                sh 'echo hello from stage 3!. This is the last stage...'
            }
        }

    }
}
